// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceBooking.API.Data;

#nullable disable

namespace ServiceBooking.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceBooking.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Status");

                    b.HasIndex("StaffId", "StartTime", "EndTime");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingCode = "BK000001",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            CustomerNote = "Cắt gọn nhẹ",
                            EndTime = new DateTime(2026, 9, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 1,
                            StaffId = 1,
                            StartTime = new DateTime(2026, 9, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            BookingCode = "BK000002",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 9, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 3,
                            StaffId = 1,
                            StartTime = new DateTime(2026, 9, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            BookingCode = "BK000003",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 9, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 2,
                            StaffId = 2,
                            StartTime = new DateTime(2026, 9, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            BookingCode = "BK000004",
                            CancellationReason = "Khách bận đột xuất",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 9, 16, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 4,
                            StaffId = 2,
                            StartTime = new DateTime(2026, 9, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 5,
                            BookingCode = "BK000005",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 9, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 5,
                            StaffId = 1,
                            StartTime = new DateTime(2026, 9, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 6,
                            BookingCode = "BK000006",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 9, 17, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 1,
                            StaffId = 1,
                            StartTime = new DateTime(2026, 9, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 7,
                            BookingCode = "BK000007",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 9, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 3,
                            StaffId = 2,
                            StartTime = new DateTime(2026, 9, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 8,
                            BookingCode = "BK000008",
                            CancellationReason = "Đổi lịch khác",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 9, 18, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 2,
                            StaffId = 1,
                            StartTime = new DateTime(2026, 9, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            Id = 9,
                            BookingCode = "BK000009",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            EndTime = new DateTime(2026, 9, 18, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 4,
                            StaffId = 2,
                            StartTime = new DateTime(2026, 9, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 10,
                            BookingCode = "BK000010",
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            EndTime = new DateTime(2026, 9, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = 5,
                            StaffId = 1,
                            StartTime = new DateTime(2026, 9, 19, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("ServiceBooking.API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cắt gọn gàng, tạo kiểu cơ bản",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Cắt tóc nam",
                            Price = 100000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Uốn nếp tự nhiên",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Uốn tóc",
                            Price = 350000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nhuộm màu theo yêu cầu",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Nhuộm tóc",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Massage thư giãn da đầu",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Gội đầu dưỡng sinh",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chăm sóc và làm sạch da mặt",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Spa da mặt",
                            Price = 400000m
                        });
                });

            modelBuilder.Entity("ServiceBooking.API.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "staff1@bookingdemo.com",
                            FullName = "Le Van Staff",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "staff2@bookingdemo.com",
                            FullName = "Pham Thi Staff",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ServiceBooking.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bookingdemo.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2b$11$8eHBHt/uDocDWkhSuExsJeCCqHt0Zwi17kdIAxLV4kJG.Q1gcqgUK",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer1@bookingdemo.com",
                            FullName = "Nguyen Van A",
                            IsActive = true,
                            PasswordHash = "$2b$11$LdAU0Mx2RLKLlBT1ur3oK.du2VYk6.LKhdYV5Om4H64j4bdJncrWW",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer2@bookingdemo.com",
                            FullName = "Tran Thi B",
                            IsActive = true,
                            PasswordHash = "$2b$11$LdAU0Mx2RLKLlBT1ur3oK.du2VYk6.LKhdYV5Om4H64j4bdJncrWW",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("ServiceBooking.API.Models.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StaffId", "WorkDate");

                    b.ToTable("WorkSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 1,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 15)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 2,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 15)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 1,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 16)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 2,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 16)
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 1,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 17)
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 2,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 17)
                        },
                        new
                        {
                            Id = 7,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 1,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 18)
                        },
                        new
                        {
                            Id = 8,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 2,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 18)
                        },
                        new
                        {
                            Id = 9,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 1,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 19)
                        },
                        new
                        {
                            Id = 10,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 2,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 19)
                        },
                        new
                        {
                            Id = 11,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 1,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 20)
                        },
                        new
                        {
                            Id = 12,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 2,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 20)
                        },
                        new
                        {
                            Id = 13,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 1,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 21)
                        },
                        new
                        {
                            Id = 14,
                            EndTime = new TimeOnly(17, 0, 0),
                            StaffId = 2,
                            StartTime = new TimeOnly(8, 0, 0),
                            WorkDate = new DateOnly(2026, 9, 21)
                        });
                });

            modelBuilder.Entity("ServiceBooking.API.Models.Booking", b =>
                {
                    b.HasOne("ServiceBooking.API.Models.User", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceBooking.API.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceBooking.API.Models.Staff", "Staff")
                        .WithMany("Bookings")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ServiceBooking.API.Models.WorkSchedule", b =>
                {
                    b.HasOne("ServiceBooking.API.Models.Staff", "Staff")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ServiceBooking.API.Models.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ServiceBooking.API.Models.Staff", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("ServiceBooking.API.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
